add (initial) support for MinGW-64
Due to implementation details of this platform, the
correct architecture needs to be given by the
"--build=x86_64-w64-mingw32" option to configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4184,6 +4184,20 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
 	AS=as
         QT_ARCH="iX86"
         ;;
+    amd64*mingw* | x86_64*mingw*)
+        case "$CXX_COMP" in
+            c++ | g++)
+                TARGET_ARCH="mingw64"
+                ;;
+            *)
+                { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
+echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
+   { (exit 1); exit 1; }; }
+            ;;
+        esac
+        AS=as
+        QT_ARCH="x86_64"
+        ;;
     *mingw*)
         case "$CXX_COMP" in
             c++ | g++)
