import (OSCI internal) SystemC version 2.2.1.06nov08_beta
Summary: import (OSCI internal) SystemC version 2.2.1.06nov08_beta
Keywords:

Imported systemc-2.2.1.06nov08_beta
into Git repository

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -57,6 +57,34 @@ CXX_COMP=`basename $CXX`
 AR_TOOL="ar cru"
 
 case "$target" in
+    i386-apple-macosx*)
+        case "$CXX_COMP" in
+            CC)
+                EXTRA_CXXFLAGS=""
+                DEBUG_CXXFLAGS="-g"
+                OPT_CXXFLAGS="-O3"
+                TARGET_ARCH="macosx386"
+		AR_TOOL="$CXX -xar -o"
+        	CC="$CXX"
+        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
+                ;;
+            c++ | g++)
+                EXTRA_CXXFLAGS="-Wall"
+                DEBUG_CXXFLAGS="-g"
+                OPT_CXXFLAGS="-O3"
+                TARGET_ARCH="macosx386"
+        	CC="$CXX"
+        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
+                ;;
+            *)
+                { { echo "$as_me:2730: error: \"sorry...compiler not supported\"" >&5
+echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+        esac
+	AS=as
+        QT_ARCH="iX86"
+        ;;
     powerpc-apple-macosx*)
         case "$CXX_COMP" in
             CC)
