Imported systemc-2.3.09jul10_beta
Summary: Imported systemc-2.3.09jul10_beta
Keywords:

Imported systemc-2.3.09jul10_beta
into Git repository

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4051,28 +4051,24 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 CXX_COMP=`basename $CXX`
 AR_TOOL="ar cru"
 
+EXTRA_CXXFLAGS="-Wall"
+DEBUG_CXXFLAGS="-g"
+OPT_CXXFLAGS="-O3"
+
 case "$target" in
     i386-apple-macosx*)
         case "$CXX_COMP" in
             CC)
                 EXTRA_CXXFLAGS="-arch i386"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="macosx386"
 		AR_TOOL="$CXX -xar -o"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall -arch i386"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
+                EXTRA_CXXFLAGS="$EXTRA_CXXFLAGS -arch i386"
                 TARGET_ARCH="macosx386"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
-                { { echo "$as_me:2730: error: \"sorry...compiler not supported\"" >&5
+		{ { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
 echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
    { (exit 1); exit 1; }; }
 		;;
@@ -4080,45 +4076,18 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
 	AS="as -arch i386"
         QT_ARCH="iX86"
         ;;
-    *mingw*)
-        case "$CXX_COMP" in
-            c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
-                TARGET_ARCH="macosx"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
-                ;;
-            *)
-                { { echo "$as_me:2730: error: \"sorry...compiler not supported\"" >&5
-echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
-   { (exit 1); exit 1; }; }
-        esac
-	AS=as
-        QT_ARCH="iX386"
-        ;;
     powerpc-apple-macosx*)
         case "$CXX_COMP" in
             CC)
                 EXTRA_CXXFLAGS=""
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="macosx"
 		AR_TOOL="$CXX -xar -o"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="macosx"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
-                { { echo "$as_me:2730: error: \"sorry...compiler not supported\"" >&5
+		{ { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
 echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
    { (exit 1); exit 1; }; }
 		;;
@@ -4130,20 +4099,11 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
         case "$CXX_COMP" in
             CC)
                 EXTRA_CXXFLAGS=""
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="sparcOS5"
 		AR_TOOL="$CXX -xar -o"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="gccsparcOS5"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
                 { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
@@ -4157,12 +4117,7 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
     x86_64*linux*)
         case "$CXX_COMP" in
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="linux64"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
                 { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
@@ -4176,12 +4131,7 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
     *linux*)
         case "$CXX_COMP" in
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="linux"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
                 { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
@@ -4190,17 +4140,40 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
 		;;
         esac
 	AS=as
+        QT_ARCH="iX86"
+        ;;
+    amd64*freebsd* | x86_64*freebsd*)
+        case "$CXX_COMP" in
+            c++ | g++)
+                TARGET_ARCH="freebsd64"
+                ;;
+            *)
+                { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
+echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
+   { (exit 1); exit 1; }; }
+            ;;
+        esac
+        AS=as
+        QT_ARCH="x86_64"
+        ;;
+    *freebsd*)
+        case "$CXX_COMP" in
+            c++ | g++)
+                TARGET_ARCH="freebsd"
+                ;;
+            *)
+                { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
+echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
+   { (exit 1); exit 1; }; }
+            ;;
+        esac
+        AS=as
         QT_ARCH="iX86"
         ;;
     *cygwin*)
         case "$CXX_COMP" in
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="cygwin"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
                 { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
@@ -4211,23 +4184,30 @@ echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
 	AS=as
         QT_ARCH="iX86"
         ;;
+    *mingw*)
+        case "$CXX_COMP" in
+            c++ | g++)
+                TARGET_ARCH="mingw"
+                ;;
+            *)
+                { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
+echo "$as_me: error: \"sorry...compiler not supported\"" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+        esac
+	AS=as
+        QT_ARCH="iX386"
+        ;;
     *hpux11*)
         case "$CXX_COMP" in
             aCC)
                 EXTRA_CXXFLAGS="-AA -ext +DA2.0 +DS2.0"
-                DEBUG_CXXFLAGS="-g"
                 OPT_CXXFLAGS="+O1"
                 TARGET_ARCH="hpux11"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS -Wa,-w36"
+        	CFLAGS="-Wa,-w36"
                 ;;
             c++ | g++)
-                EXTRA_CXXFLAGS="-Wall"
-                DEBUG_CXXFLAGS="-g"
-                OPT_CXXFLAGS="-O3"
                 TARGET_ARCH="gcchpux11"
-        	CC="$CXX"
-        	CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS"
                 ;;
             *)
                 { { echo "$as_me:$LINENO: error: \"sorry...compiler not supported\"" >&5
@@ -4244,6 +4224,9 @@ echo "$as_me: error: \"sorry...architecture not supported\"" >&2;}
    { (exit 1); exit 1; }; }
         ;;
 esac
+
+CC="$CXX"
+CFLAGS="$EXTRA_CXXFLAGS $OPT_CXXFLAGS $EXTRA_CFLAGS"
 
 
 EXTRA_CXXFLAGS="$EXTRA_CXXFLAGS -DSC_INCLUDE_FX"
